id: ACBA1C83C
base_file: fFC65.txt
type: translation
source_metadata:
  languages:
  - en
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-06-17 13:51:04.981378
  last_modified_at: 2022-06-17 13:51:04.981381
