id: ACBA1C83C
base_file: f3A64.txt
type: translation
source_metadata:
  languages:
  - en
  - es
  - bo
  datatype: PlainText
  created_at: 2022-06-17 13:51:04.810061
  last_modified_at: 2022-06-17 13:51:04.810064
