id: ACBA1C83C
base_file: f61E4.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-06-17 13:51:04.845925
  last_modified_at: 2022-06-17 13:51:04.845927
