id: ACBA1C83C
base_file: f5A25.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-06-17 13:51:04.839295
  last_modified_at: 2022-06-17 13:51:04.839303
