id: ACBA1C83C
base_file: f224C.txt
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-06-17 13:51:04.784204
  last_modified_at: 2022-06-17 13:51:04.784207
