id: ACBA1C83C
base_file: f9393.txt
type: translation
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-06-17 13:51:04.870818
  last_modified_at: 2022-06-17 13:51:04.870821
