id: ACBA1C83C
base_file: f454E.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-06-17 13:51:04.818588
  last_modified_at: 2022-06-17 13:51:04.818592
