id: ACBA1C83C
base_file: f3969.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - it
  - nl
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-06-17 13:51:04.806153
  last_modified_at: 2022-06-17 13:51:04.806156
