id: ACBA1C83C
base_file: fD534.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-06-17 13:51:04.943028
  last_modified_at: 2022-06-17 13:51:04.943031
