id: ACBA1C83C
base_file: fBACB.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 13:51:04.933335
  last_modified_at: 2022-06-17 13:51:04.933338
