id: ACBA1C83C
base_file: f7EDD.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - bo
  datatype: PlainText
  created_at: 2022-06-17 13:51:04.866567
  last_modified_at: 2022-06-17 13:51:04.866570
